CREATE TABLE `ITINERARY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER` varchar(255) DEFAULT NULL,
  `SERVICE` varchar(255) NOT NULL,
  `OPERATION` varchar(255) DEFAULT NULL,
  `PRIORITY` bigint(20) NOT NULL,
  `EXPIRATION_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `CONTEXT_AWARE_ADAPTATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `ITINERARY_ID` bigint(20) NOT NULL,
  `DATA` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ADAPTATION_1` (`ITINERARY_ID`),
  CONSTRAINT `FK_ADAPTATION_1` FOREIGN KEY (`ITINERARY_ID`) REFERENCES `ITINERARY` (`ID`)
)ENGINE=InnoDB;  
