CREATE TABLE `SITUATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `SERVICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SERVICE_NAME` varchar(255) NOT NULL,
  `OPERATION_NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `ADAPTATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `SITUATION_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  `DATA_TYPE` varchar(255) DEFAULT NULL,
  `DATA` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ADAPTATION_1` (`SITUATION_ID`),
  KEY `FK_ADAPTATION_2` (`SERVICE_ID`),
  CONSTRAINT `FK_ADAPTATION_1` FOREIGN KEY (`SITUATION_ID`) REFERENCES `SITUATION` (`ID`),
  CONSTRAINT `FK_ADAPTATION_2` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`ID`)
) ENGINE=InnoDB;  
