CREATE TABLE `RULE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `VERSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION_NUMBER` varchar(255) NOT NULL,
  `CREATION_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `RULE_VERSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DRL` varbinary(5000) NOT NULL,
  `RULE_ID` bigint(20) DEFAULT NULL,
  `VERSION_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RULE_VERSION_1` (`RULE_ID`),
  KEY `FK_RULE_VERSION_2` (`VERSION_ID`),
  CONSTRAINT `FK_RULE_VERSION_1` FOREIGN KEY (`RULE_ID`) REFERENCES `RULE` (`ID`),
  CONSTRAINT `FK_RULE_VERSION_2` FOREIGN KEY (`VERSION_ID`) REFERENCES `VERSION` (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `ACTIVE_CONFIGURATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LAST_DEPLOY_DATE`  DATETIME DEFAULT NULL,
  `ACTIVE_VERSION_ID` bigint(20) DEFAULT NULL,
  `LAST_VERSION_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ACTIVE_CONFIGURATION_1` (`ACTIVE_VERSION_ID`),
  KEY `FK_ACTIVE_CONFIGURATION_2` (`LAST_VERSION_ID`),
  CONSTRAINT `FK_ACTIVE_CONFIGURATION_1` FOREIGN KEY (`ACTIVE_VERSION_ID`) REFERENCES `VERSION` (`ID`),
  CONSTRAINT `FK_ACTIVE_CONFIGURATION_2` FOREIGN KEY (`LAST_VERSION_ID`) REFERENCES `VERSION` (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `CONTEXT_DATUM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `CONTEXT_SOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `PROPERTIES` varbinary(5000) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `CONTEXT_SOURCE_DATUM` (
  `CONTEXT_SOURCE_ID` bigint(20) NOT NULL,
  `CONTEXT_DATUM_ID` bigint(20) NOT NULL,
   PRIMARY KEY (`CONTEXT_SOURCE_ID`,`CONTEXT_DATUM_ID`)
) ENGINE=InnoDB; 

CREATE TABLE `SITUATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DURATION` bigint(20) DEFAULT NULL,
  `RULE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SITUATION_1` (`RULE_ID`),
  CONSTRAINT `FK_SITUATION_1` FOREIGN KEY (`RULE_ID`) REFERENCES `RULE` (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `SITUATION_INPUT_CONTEXT_DATUM` (
  `SITUATION_ID` bigint(20) NOT NULL,
  `CONTEXT_DATUM_ID` bigint(20) NOT NULL,
   PRIMARY KEY (`SITUATION_ID`,`CONTEXT_DATUM_ID`)
) ENGINE=InnoDB; 

CREATE TABLE `SITUATION_OUTPUT_CONTEXT_DATUM` (
  `SITUATION_ID` bigint(20) NOT NULL,
  `CONTEXT_DATUM_ID` bigint(20) NOT NULL,
   PRIMARY KEY (`SITUATION_ID`,`CONTEXT_DATUM_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SITUATION_CONTEXT_SOURCE` (
  `SITUATION_ID` bigint(20) NOT NULL,
  `CONTEXT_SOURCE_ID` bigint(20) NOT NULL,
   PRIMARY KEY (`SITUATION_ID`,`CONTEXT_SOURCE_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SERVICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SERVICE_NAME` varchar(255) NOT NULL,
  `OPERATION_NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `SERVICE_SITUATION_PRIORITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRIORITY` bigint(20) NOT NULL,
  `SITUATION_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`, `SITUATION_ID`, `SERVICE_ID`),
  KEY `FK_SERVICE_SITUATION_PRIORITY_1` (`SITUATION_ID`),
  KEY `FK_SERVICE_SITUATION_PRIORITY_2` (`SERVICE_ID`),
  CONSTRAINT `FK_SERVICE_SITUATION_PRIORITY_1` FOREIGN KEY (`SITUATION_ID`) REFERENCES `SITUATION` (`ID`),
  CONSTRAINT `FK_SERVICE_SITUATION_PRIORITY_2` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`ID`),
  CONSTRAINT `UQ_SERVICE_SITUATION_PRIORITY` UNIQUE(SITUATION_ID, SERVICE_ID)
) ENGINE=InnoDB;

CREATE TABLE `ADAPTATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ADAPTATION_ORDER` int(4) NOT NULL,
  `SITUATION_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  `ADAPTATION_TYPE` varchar(255) NOT NULL,
  `DATA` varbinary(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`, `SITUATION_ID`, `SERVICE_ID`),
  KEY `FK_ADAPTATION_1` (`SITUATION_ID`),
  KEY `FK_ADAPTATION_2` (`SERVICE_ID`),
  CONSTRAINT `FK_ADAPTATION_1` FOREIGN KEY (`SITUATION_ID`) REFERENCES `SITUATION` (`ID`),
  CONSTRAINT `FK_ADAPTATION_2` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`ID`)
) ENGINE=InnoDB;  