CREATE TABLE `SITUATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `MINUTE_DURATION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB; 

CREATE TABLE `SERVICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SERVICE_NAME` varchar(255) NOT NULL,
  `OPERATION_NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `ADAPTATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ORDER` int(4) NOT NULL,
  `SITUATION_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  `ADAPTATION_REFERENCE_ID` bigint(20) NOT NULL,
  `DATA` varbinary(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ADAPTATION_1` (`SITUATION_ID`),
  KEY `FK_ADAPTATION_2` (`SERVICE_ID`),
  KEY `FK_ADAPTATION_3` (`ADAPTATION_REFERENCE_ID`),
  CONSTRAINT `FK_ADAPTATION_1` FOREIGN KEY (`SITUATION_ID`) REFERENCES `SITUATION` (`ID`),
  CONSTRAINT `FK_ADAPTATION_2` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`ID`),
  CONSTRAINT `FK_ADAPTATION_3` FOREIGN KEY (`ADAPTATION_REFERENCE_ID`) REFERENCES `ADAPTATION_REFERENCE` (`ID`)
) ENGINE=InnoDB;  

CREATE TABLE `SERVICE_SITUATION_PRIORITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRIORITY` bigint(20) NOT NULL,
  `SITUATION_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SERVICE_SITUATION_PRIORITY_1` (`SITUATION_ID`),
  KEY `FK_SERVICE_SITUATION_PRIORITY_2` (`SERVICE_ID`),
  CONSTRAINT `FK_SERVICE_SITUATION_PRIORITY_1` FOREIGN KEY (`SITUATION_ID`) REFERENCES `SITUATION` (`ID`),
  CONSTRAINT `FK_SERVICE_SITUATION_PRIORITY_2` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `ADAPTATION_REFERENCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ADAPTATION_TYPE` varchar(255) NOT NULL,
  `URI` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;