package com.example.switchyard.example
import org.switchyard.Message
global Message message

rule "RulesComponent"
    when
        $userLoc : UserLocation
    then
    	InCity userInCity = new InCity();
    	userInCity.setCiudad($userLoc.getCiudad());
    	userInCity.setUserId($userLoc.getUserId);
    	userInCity.setTimestamp($userLoc.getTimeStamp());
    	insert(userInCity);
        // insert consequence here
        System.out.println("service: ServicioCEP, payload: " + message.getContent());
end
